"""Visualization gallery: the result figures the notebooks already produced."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import _bootstrap  # noqa: F401,E402
import streamlit as st  # noqa: E402

from core.loaders import load_table, load_text, result_files_by_kind  # noqa: E402
from ui import repo_note, result_gallery, setup_page  # noqa: E402

setup_page("Visualizations", "🖼️")
repo_note()

st.caption(
    "A gallery of the images and summary tables generated by the notebooks. "
    "They are displayed exactly as saved — the app does not regenerate plots."
)

tab_clf, tab_reg, tab_clu, tab_tables = st.tabs(
    ["🚨 Classification", "🌡️ Regression", "🧩 Clustering", "📄 Tables & text"]
)

TRACKS = {
    "classification": ("🚨 Classification", tab_clf),
    "regression": ("🌡️ Regression", tab_reg),
    "clustering": ("🧩 Clustering", tab_clu),
}

for track, (label, tab) in TRACKS.items():
    with tab:
        files = result_files_by_kind(track)
        if not files["images"]:
            st.info(f"No result images found for the {track} track.")
        else:
            st.markdown(f"**{len(files['images'])} figure(s)**")
            result_gallery(files["images"], columns=2)

        if files["tables"]:
            with st.expander(f"Summary tables ({len(files['tables'])})"):
                for path in files["tables"]:
                    st.markdown(f"**{path.name}**")
                    st.dataframe(load_table(path), use_container_width=True)

        if files["text"]:
            with st.expander(f"Reports ({len(files['text'])})"):
                for path in files["text"]:
                    st.markdown(f"**{path.name}**")
                    st.code(load_text(path), language="text")

with tab_tables:
    st.subheader("All result files by track")
    rows = []
    for track in ("classification", "regression", "clustering"):
        files = result_files_by_kind(track)
        for kind, paths in files.items():
            for path in paths:
                rows.append({"Track": track, "Kind": kind, "File": path.name})
    st.dataframe(rows, use_container_width=True)
    st.caption(
        "Files whose names begin with `_` (such as export logs) are intentionally hidden."
    )
